<?PHP
//header('Content-Type: text/html; charset=utf-8');
session_cache_expire(1800);
//현재 페이지에만 임의로 1800을 줍니다.
session_start();
?>

<?php
include_once ('../php/config.php');
//SELECT USER_ID, USER_NICKNAME, IP_ADDRESS, MAC_ADDRESS, GATEWAY, E_MAIL, BLACK_FLAG, USER_BYTE_COUNT_SRC, USER_PACKET_COUNT_SRC, USER_START_TIME_SRC, USER_BYTE_COUNT_DST, USER_PACKET_COUNT_DST, USER_START_TIME_DST FROM USER, (SELECT NETFLOWENTRY.SRC_ADDR AS USER_SRC_ADDR, NETFLOWENTRY.BYTE_COUNT AS USER_BYTE_COUNT_SRC, NETFLOWENTRY.PACKET_COUNT AS USER_PACKET_COUNT_SRC, MAX(NETFLOWENTRY.START_TIME) AS USER_START_TIME_SRC FROM NETFLOWENTRY, (SELECT DISTINCT N.SRC_ADDR AS USER_IP FROM NETFLOWENTRY AS N, USER AS U WHERE N.SRC_ADDR=U.IP_ADDRESS AND U.ACCEPT='administrator')x WHERE NETFLOWENTRY.SRC_ADDR=USER_IP GROUP BY NETFLOWENTRY.SRC_ADDR) AS UNS, (SELECT NETFLOWENTRY.DST_ADDR AS USER_DST_ADDR, NETFLOWENTRY.BYTE_COUNT AS USER_BYTE_COUNT_DST, NETFLOWENTRY.PACKET_COUNT AS USER_PACKET_COUNT_DST, MAX(NETFLOWENTRY.START_TIME) AS USER_START_TIME_DST FROM NETFLOWENTRY, (SELECT DISTINCT N2.DST_ADDR AS USER_IP FROM NETFLOWENTRY AS N2, USER AS U2 WHERE N2.DST_ADDR=U2.IP_ADDRESS AND U2.ACCEPT='administrator')y WHERE NETFLOWENTRY.DST_ADDR=USER_IP GROUP BY NETFLOWENTRY.DST_ADDR) AS UND WHERE USER.IP_ADDRESS=UNS.USER_SRC_ADDR AND USER.IP_ADDRESS=UND.USER_DST_ADDR;
mysql_select_db($SGdb, $conn);
// Accept 된 유저중 들어오는거 따로 나가는것 따로 패킷카운트랑 바이트 카운트 구하는것
$q="
		SELECT USER_ID, USER_NICKNAME, IP_ADDRESS, MAC_ADDRESS, GATEWAY, E_MAIL, BLACK_FLAG, USER_BYTE_COUNT_SRC, USER_PACKET_COUNT_SRC, USER_START_TIME_SRC, USER_BYTE_COUNT_DST, USER_PACKET_COUNT_DST, USER_START_TIME_DST FROM USER, (SELECT NETFLOWENTRY.SRC_ADDR AS USER_SRC_ADDR, NETFLOWENTRY.BYTE_COUNT AS USER_BYTE_COUNT_SRC, NETFLOWENTRY.PACKET_COUNT AS USER_PACKET_COUNT_SRC, MAX(NETFLOWENTRY.START_TIME) AS USER_START_TIME_SRC FROM NETFLOWENTRY, (SELECT DISTINCT N.SRC_ADDR AS USER_IP FROM NETFLOWENTRY AS N, USER AS U WHERE N.SRC_ADDR=U.IP_ADDRESS AND U.ACCEPT='".$_SESSION["session__id"]."')x WHERE NETFLOWENTRY.SRC_ADDR=USER_IP GROUP BY NETFLOWENTRY.SRC_ADDR) AS UNS, (SELECT NETFLOWENTRY.DST_ADDR AS USER_DST_ADDR, NETFLOWENTRY.BYTE_COUNT AS USER_BYTE_COUNT_DST, NETFLOWENTRY.PACKET_COUNT AS USER_PACKET_COUNT_DST, MAX(NETFLOWENTRY.START_TIME) AS USER_START_TIME_DST FROM NETFLOWENTRY, (SELECT DISTINCT N2.DST_ADDR AS USER_IP FROM NETFLOWENTRY AS N2, USER AS U2 WHERE N2.DST_ADDR=U2.IP_ADDRESS AND U2.ACCEPT='".$_SESSION["session__id"]."')y WHERE NETFLOWENTRY.DST_ADDR=USER_IP GROUP BY NETFLOWENTRY.DST_ADDR) AS UND WHERE USER.IP_ADDRESS=UNS.USER_SRC_ADDR AND USER.IP_ADDRESS=UND.USER_DST_ADDR";
$sql_result=mysql_query($q, $conn);          //질의(위 내용)를 수행하라.


$count=mysql_num_rows($sql_result);          //mysql_num_rows() 함수 : 행의 개수를 세는 함수.
echo("<script>Qcount=$count;</script>");
// echo $count;     //mysql query 수행 후 반환되는 결과값을 매개변수로 받고 그 레코드의 개수를 반환

// echo "<br><br>";

//mysql_result(쿼리실행결과, 행번호, 변수값) : 결과값을 행 단위로 화면에 출력해주는 함수.

for($i=0; $i<$count; $i++)
{
	$dbUSER_ID[$i]=mysql_result($sql_result, $i, USER_ID);
	$dbUSER_NICKNAME[$i]=mysql_result($sql_result, $i, USER_NICKNAME);
	$dbIP_ADDRESS[$i]=mysql_result($sql_result, $i, IP_ADDRESS);
	$dbMAC_ADDRESS[$i]=mysql_result($sql_result, $i, MAC_ADDRESS);
	$dbGATEWAY[$i]=mysql_result($sql_result, $i, GATEWAY);
	$dbE_MAIL[$i]=mysql_result($sql_result, $i, E_MAIL);
	$dbBLACK_FLAG[$i]=mysql_result($sql_result, $i, BLACK_FLAG);

	$dbUSER_BYTE_COUNT_SRC[$i]=mysql_result($sql_result, $i, USER_BYTE_COUNT_SRC);
	$dbUSER_PACKET_COUNT_SRC[$i]=mysql_result($sql_result, $i, USER_PACKET_COUNT_SRC);
	$dbUSER_START_TIME_SRC[$i]=mysql_result($sql_result, $i, USER_START_TIME_SRC);

	$dbUSER_BYTE_COUNT_DST[$i]=mysql_result($sql_result, $i, USER_BYTE_COUNT_DST);
	$dbUSER_PACKET_COUNT_DST[$i]=mysql_result($sql_result, $i, USER_PACKET_COUNT_DST);
	$dbUSER_START_TIME_DST[$i]=mysql_result($sql_result, $i, USER_START_TIME_DST);
}

echo("<script>num=0;</script>");
for($i=0; $i<$count; $i++){
	//$changBYTE_COUNT=round($dbBYTE_COUNT_TCP[$i]/pow(1024,1)*10)/10;
	$changUSER_BYTE_COUNT_SRC=round($dbUSER_BYTE_COUNT_SRC[$i]/pow(1024,1)*10)/10;
	$changUSER_BYTE_COUNT_DST=round($dbUSER_BYTE_COUNT_DST[$i]/pow(1024,1)*10)/10;
	echo ("<script>
			USER_ID[num]='$dbUSER_ID[$i]';
			USER_NICKNAME[num]='$dbUSER_NICKNAME[$i]';
			IP_ADDRESS[num]='$dbIP_ADDRESS[$i]';
			MACK_ADDRESS[num]='$dbMAC_ADDRESS[$i]';
			GATEWAY[num]='$dbGATEWAY[$i]';
			E_MAIL[num]='$dbE_MAIL[$i]';
			BLACK_FLAG[num]='$dbBLACK_FLAG[$i]';
				
			USER_BYTE_COUNT_SRC[num]='$changUSER_BYTE_COUNT_SRC';
			USER_PACKET_COUNT_SRC[num]='$dbUSER_PACKET_COUNT_SRC[$i]';
			USER_START_TIME_SRC[num]='$dbUSER_START_TIME_SRC[$i]';
				
			USER_BYTE_COUNT_DST[num]='$changUSER_BYTE_COUNT_DST';
			USER_PACKET_COUNT_DST[num]='$dbUSER_PACKET_COUNT_DST[$i]';
			USER_START_TIME_DST[num]='$dbUSER_START_TIME_DST[$i]';
			</script>");
	echo("<script>num++;</script>");
}
?>
